name: Continuous Integration for Serverless Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS Credentials
      run: echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > $GITHUB_WORKSPACE/.env

    - name: Set up CodeCommit Credentials
      run: echo "[credential]" >> ~/.git-credentials && echo "    helper = !aws codecommit credential-helper $@" >> ~/.git-credentials
      env:
        CODECOMMIT_REPO_URL: ${{ secrets.CODECOMMIT_REPO_URL }}
        CODECOMMIT_GIT_CREDENTIAL: ${{ secrets.CODECOMMIT_GIT_CREDENTIAL }}
        CODECOMMIT_IAM_USERNAME: ${{ secrets.CODECOMMIT_IAM_USERNAME }}
        CODECOMMIT_IAM_PASSWORD: ${{ secrets.CODECOMMIT_IAM_PASSWORD }}

    - name: Configure Git for CodeCommit
      run: git config --global credential.helper 'store --file ~/.git-credentials'

 #   - name: Add AWS CodeCommit Remote
 #     run: git remote add codecommit $CODECOMMIT_REPO_URL

    - name: Push to CodeCommit
      run: git push codecommit HEAD:main
      env:
        GIT_COMMITTER_NAME: $GIT_COMMITTER_NAME
        GIT_COMMITTER_EMAIL: $GIT_COMMITTER_EMAIL
