name: sync up to codecommit

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: git config --global --add safe.directory /github/workspace

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Run Wild-Rydes
        uses: lateef-taiwo/Wild-Rydes@main
        with:
          repository_name: wild-rides-repo
          aws_region: us-east-1
        env:
            AWS_DEFAULT_REGION: us-east-1
            AWS_REGION: us-east-1
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            DEBUG: 'true'


      - name: Sync up to CodeCommit
        uses: lateef-taiwo/Wild-Rydes@main
        with:
          repository_name: wild-rides-repo
          aws_region: us-east-1


#Workflows
